[package]
name = "osql_parser_derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.8.0"
darling = "0.20.11"
deluxe = "0.5.0"
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.101"
unsynn = "0.1.1"

